[package]
name = "rp"
version = "0.1.0"
authors = ["Li Jinpei <leekingp1994@163.com>"]
edition = "2018"

[dependencies]

enum_dispatch = { git = "https://gitlab.com/lijinpei/enum_dispatch", branch = "tls" }
